### ISSUE TITLE
Fix some crash reported on discord

### ISSUE THREAD

**Issue by RkShaRkz** [RkShaRkz/Starsector-IntelliJ-Template#11]
```
1775427 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.loading.IndustrySpecAPI.getBuildTime()" because "upgrade" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.api.loading.IndustrySpecAPI.getBuildTime()" because "upgrade" is null
    at com.fs.starfarer.api.impl.campaign.econ.impl.BaseIndustry.startUpgrading(BaseIndustry.java:572) ~[starfarer.api.jar:?]
    at data.scripts.campaign.colonies.VayraColonialManager.pickNextUpgrade(VayraColonialManager.java:655) ~[?:?]
    at data.scripts.campaign.fleets.VayraPopularFrontManager.advance(VayraPopularFrontManager.java:83) ~[?:?]
```

take a look at this, and nullguard as necessary.

**Comment by RkShaRkz** [comment]
line 655 isn't even a part of `pickNextUpgrade()` method, so the stacktrace is anapplicable. Will have to wait for this one to reappear
