### ISSUE TITLE
Crash in the middle of a combat

### ISSUE THREAD

**Issue by Tick-Tock-Man** [RkShaRkz/Starsector-IntelliJ-Template#31]
Seems to be Vayra D-Mod related, the crash log is posted below:

2930236 [Thread-2] INFO  sound.O  - Cleaning up music with id [campaign_noncore_part1.ogg]
2930249 [Thread-6] INFO  sound.O  - Cleaning up music with id [battle_ambience_01.ogg]
2930394 [Thread-9] INFO  sound.O  - Creating streaming player for music with id [battle_ambience_01.ogg]
2930394 [Thread-9] INFO  sound.OooO  - Playing music with id [battle_ambience_01.ogg]
2931272 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Objects.java:365) ~[?:?]
        at java.base/java.util.ArrayList.set(ArrayList.java:471) ~[?:?]
        at data.scripts.hullmods.VayraDamagedOptics.advanceInCombat(VayraDamagedOptics.java:41) ~[?:?]
        at com.fs.starfarer.combat.entities.Ship.advance(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.combat.CombatState.traverse(Unknown Source) ~[port_obf.jar:?]
        at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
        at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]

**Comment by RkShaRkz** [comment]
Closing until issue resurfaces again in 3.3.9
