### ISSUE TITLE
fix bullshit vayra's derelict ship distress call's shipRole distribution [VayraGhostShipDistressCall's spawnWreck() method]

### ISSUE THREAD

**Issue by GreyBirb** [RkShaRkz/Starsector-IntelliJ-Template#4]
//Game Version: 0.97a-RC11

//Crash:

java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Float (java.lang.String and java.lang.Float are in module java.base of loader 'bootstrap')
    at com.fs.starfarer.api.impl.campaign.DerelictShipEntityPlugin.pickVariant(DerelictShipEntityPlugin.java:190) ~[starfarer.api.jar:?]
    at data.scripts.campaign.events.VayraGhostShipDistressCall.spawnWreck(VayraGhostShipDistressCall.java:90) ~[?:?]
    at data.scripts.campaign.events.VayraGhostShipDistressCall.setup(VayraGhostShipDistressCall.java:65) ~[?:?]
    at data.scripts.campaign.events.VayraGhostShipDistressCall.advance(VayraGhostShipDistressCall.java:46) ~[?:?]
    at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
    at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
    at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
    at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
    at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]

  //The part that causes the sector crash during Vayra's sector derelict generation
  
 WeightedRandomPicker<String> picker = new WeightedRandomPicker<String>(random);
        for (int i = 0; i < shipRoles.length; i += 2) {
            String role = (String) shipRoles[i];
            Float weight = (Float) shipRoles[i + 1];  //crashes here
            picker.add(role, weight);
        }
        
        //The part that needs fixing:
        
          variantId = pickVariant(faction, new Random(),
                    ShipRoles.COMBAT_LARGE,
                    ShipRoles.COMBAT_CAPITAL,
                    ShipRoles.COMBAT_CAPITAL,
                    ShipRoles.CARRIER_MEDIUM,
                    ShipRoles.CARRIER_LARGE
            );

**Comment by GreyBirb** [comment]
Mod list:
[ModList.json](https://github.com/user-attachments/files/15941964/ModList.json)
Crash log:
[CrashLog.txt](https://github.com/user-attachments/files/15941962/CrashLog.txt)

**Comment by GreyBirb** [comment]
Save File with Crash: 
[Happens while flying from the starting location (after loading in) to the Lethia star system in hyperspace]

https://drive.google.com/drive/folders/1uWC9Smi6Y2HU2BBMKA-dzEx5EZ4s1N5I?usp=sharing

**Comment by RkShaRkz** [comment]
as discussed offline, the hotfix i made in commit 25c7a826 has indeed fixed it.

**Comment by RkShaRkz** [comment]
Fixed in new 3.3.4 release - https://github.com/RkShaRkz/Starsector-IntelliJ-Template/releases/tag/release-vayra-merged-v3.3.4
Closing issue.

**Comment by Zeta-Zhang** [comment]
The issue seems to be re-emerging as of the 3.3.6 release.
Here goes the log for cross-reference

[Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Float (java.lang.Integer and java.lang.Float are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Float (java.lang.Integer and java.lang.Float are in module java.base of loader 'bootstrap')
	at com.fs.starfarer.api.impl.campaign.DerelictShipEntityPlugin.pickVariant(DerelictShipEntityPlugin.java:190) ~[starfarer.api.jar:?]
	at data.scripts.campaign.events.VayraGhostShipDistressCall.spawnWreck(VayraGhostShipDistressCall.java:90) ~[?:?]
	at data.scripts.campaign.events.VayraGhostShipDistressCall.setup(VayraGhostShipDistressCall.java:65) ~[?:?]
	at data.scripts.campaign.events.VayraGhostShipDistressCall.advance(VayraGhostShipDistressCall.java:46) ~[?:?]
	at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]

**Comment by RkShaRkz** [comment]
> The issue seems to be re-emerging as of the 3.3.6 release. Here goes the log for cross-reference
> 
> [Thread-2] ERROR com.fs.starfarer.combat.CombatMain - java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Float (java.lang.Integer and java.lang.Float are in module java.base of loader 'bootstrap') java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Float (java.lang.Integer and java.lang.Float are in module java.base of loader 'bootstrap') at com.fs.starfarer.api.impl.campaign.DerelictShipEntityPlugin.pickVariant(DerelictShipEntityPlugin.java:190) ~[starfarer.api.jar:?] at data.scripts.campaign.events.VayraGhostShipDistressCall.spawnWreck(VayraGhostShipDistressCall.java:90) ~[?:?] at data.scripts.campaign.events.VayraGhostShipDistressCall.setup(VayraGhostShipDistressCall.java:65) ~[?:?] at data.scripts.campaign.events.VayraGhostShipDistressCall.advance(VayraGhostShipDistressCall.java:46) ~[?:?] at com.fs.starfarer.campaign.CampaignEngine.advance(Unknown Source) ~[port_obf.jar:?] at com.fs.starfarer.campaign.CampaignState.advance(Unknown Source) ~[port_obf.jar:?] at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?] at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?] at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?] at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?] at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?] at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]

That's a different issue.  Fixed by commit 3a8aec105b3a8f00351d02510bd9adf48dcde9d6 (in the still un-released 3.3.7 version)
