### ISSUE TITLE
[Crash] vayra 3.3.13 new game crash

### ISSUE THREAD

**Issue by lilstrip** [RkShaRkz/Starsector-IntelliJ-Template#69]
```
<@550049413880348682> 3481401 [Thread-2] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.loading.SkillSpec.isAptitudeEffect()" because the return value of "com.fs.starfarer.campaign.CharacterStats$SkillLevel.getSkill()" is null
java.lang.NullPointerException: Cannot invoke "com.fs.starfarer.loading.SkillSpec.isAptitudeEffect()" because the return value of "com.fs.starfarer.campaign.CharacterStats$SkillLevel.getSkill()" is null
        at com.fs.starfarer.campaign.CharacterStats.refreshCharacterStatsEffects(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.campaign.CharacterStats.refreshCharacterStatsEffects(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.addCommanderSkills(FleetFactoryV3.java:1192) ~[starfarer.api.jar:?]
        at com.fs.starfarer.api.impl.campaign.fleets.FleetFactoryV3.addCommanderSkills(FleetFactoryV3.java:1904) ~[starfarer.api.jar:?]
        at data.scripts.campaign.intel.VayraPersonBountyIntel.spawnFleet(VayraPersonBountyIntel.java:1081) ~[?:?]
        at data.scripts.campaign.intel.VayraPersonBountyIntel.<init>(VayraPersonBountyIntel.java:206) ~[?:?]
        at data.scripts.campaign.intel.VayraPersonBountyManager.createEvent(VayraPersonBountyManager.java:359) ~[?:?]
        at data.scripts.campaign.intel.VayraPersonBountyManager.advance(VayraPersonBountyManager.java:333) ~[?:?]
        at data.scripts.VayraMergedModPlugin.onNewGameAfterTimePass(VayraMergedModPlugin.java:368) ~[?:?]
        at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.ui.O.dismiss(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.ui.impl.for.dismiss(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.campaign.save.if.actionPerformed(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.ui.o0O0.buttonPressed(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.ui.int.├Æ00000(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.ui.int.processInput(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.ui.W.o00000(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
        at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
        at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
        at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

**Comment by RkShaRkz** [comment]
@lilstrip so which other mod is hiding the character skills? This is most certainly a mod-compatibility issue.

Does the issue repro when only VayraMerged is being used? And if not, which MOD ID is making it do this?

**Comment by RkShaRkz** [comment]
@lilstrip so which other mod is hiding the character skills? This is most certainly a mod-compatibility issue.

Does the issue repro when only VayraMerged is being used? And if not, which MOD ID is making it do this.

**Comment by RkShaRkz** [comment]
Try to repro using code from here https://github.com/RkShaRkz/Starsector-IntelliJ-Template/pull/73

**Comment by RkShaRkz** [comment]
Duplicate of #82 - closing.
