### ISSUE TITLE
Check some crash during WorldGen related to "vayra_kadur_refugees" missing industry

### ISSUE THREAD

**Issue by RkShaRkz** [RkShaRkz/Starsector-IntelliJ-Template#7]
Some guy on discord posted a 50mb starsector log with this crash at the end:
```
java.lang.RuntimeException: Industry [vayra_kadur_refugees] not found
	at com.fs.starfarer.campaign.econ.Market.addIndustry(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.econ.Market.addIndustry(Unknown Source) ~[port_obf.jar:?]
	at data.scripts.VayraMergedModPlugin.addMarketplace(VayraMergedModPlugin.java:472) ~[?:?]
	at data.scripts.world.systems.KadurMirageSystem.generate(KadurMirageSystem.java:168) ~[?:?]
	at data.scripts.world.KadurGen.generate(KadurGen.java:18) ~[?:?]
	at data.scripts.VayraMergedModPlugin.genKadur(VayraMergedModPlugin.java:441) ~[?:?]
	at data.scripts.VayraMergedModPlugin.onNewGame(VayraMergedModPlugin.java:307) ~[?:?]
	at com.fs.starfarer.campaign.save.CampaignGameManager.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.title.TitleScreenState.dialogDismissed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.O.dismiss(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.impl.for.dismiss(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.campaign.save.if.actionPerformed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.o0O0.buttonPressed(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.int.Ò00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.int.processInput(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.ui.W.o00000(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source) ~[port_obf.jar:?]
	at com.fs.state.AppDriver.begin(Unknown Source) ~[port.common_obf.jar:?]
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher.super(Unknown Source) ~[port_obf.jar:?]
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source) ~[port_obf.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]
```

since he couldn't even bother to post the modlist he used with the mod when it crashed, just verify with the latest version on a new save.

If it crashes, look into `VayraMergedModPlugin::getKadur()` -> `KadurGen::generate()` -> `KadurMirageSystem::generate()` -> then see what the debugger has to say about this.

If it doesn't crash, close as non-issue with lack of repro steps.

**Comment by RkShaRkz** [comment]
Started a brand new game right off the bat. Seems to be a  non-issue as I can't reproduce it. Working with someone to maybe get them to repro it with the mod zip i packaged and get screenshots to repro it on my end.

**Comment by RkShaRkz** [comment]
As I initially thought, the issue is a non-issue, it was something on their end, quite possibly a bad deployment. Distributing the mod zip alongside the sourcecode definitely addressed the problem.
